apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: nxrm-pooler
  namespace: cnpg
spec:
  cluster:
    name: nxrm-postgres
  instances: 3
  type: rw
  pgbouncer:
    poolMode: transaction
    parameters:
      max_client_conn: "100"
      default_pool_size: "20"
